// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aula03.Models;

#nullable disable

namespace aula03.Migrations
{
    [DbContext(typeof(FloriculturaContexto))]
    [Migration("20230417231423_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("aula03.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("aula03.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Estoque", (string)null);
                });

            modelBuilder.Entity("aula03.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cliente_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cliente_Id");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("aula03.Models.PedidoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pedido_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Produto_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Pedido_Id");

                    b.HasIndex("Produto_Id");

                    b.ToTable("PedidoProdutos");
                });

            modelBuilder.Entity("aula03.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estoque_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Estoque_Id")
                        .IsUnique();

                    b.HasIndex("Tipo_Id");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("aula03.Models.TipoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tipo_Produto", (string)null);
                });

            modelBuilder.Entity("aula03.Models.Pedido", b =>
                {
                    b.HasOne("aula03.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("Cliente_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("aula03.Models.PedidoProduto", b =>
                {
                    b.HasOne("aula03.Models.Produto", "Produto")
                        .WithMany("Pedidos")
                        .HasForeignKey("Pedido_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_Pedido");

                    b.HasOne("aula03.Models.Pedido", "Pedido")
                        .WithMany("Produtos")
                        .HasForeignKey("Produto_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Produto");

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("aula03.Models.Produto", b =>
                {
                    b.HasOne("aula03.Models.Estoque", "Estoque")
                        .WithOne("Produto")
                        .HasForeignKey("aula03.Models.Produto", "Estoque_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_Estoque");

                    b.HasOne("aula03.Models.TipoProduto", "Tipo")
                        .WithMany("Produtos")
                        .HasForeignKey("Tipo_Id")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_Tipo");

                    b.Navigation("Estoque");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("aula03.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("aula03.Models.Estoque", b =>
                {
                    b.Navigation("Produto")
                        .IsRequired();
                });

            modelBuilder.Entity("aula03.Models.Pedido", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("aula03.Models.Produto", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("aula03.Models.TipoProduto", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
