// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ex2.Context;

#nullable disable

namespace ex1.Migrations
{
    [DbContext(typeof(BercarioContexto))]
    [Migration("20230418192322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ex2.Models.BebeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Altura")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Mae")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id_Parto")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Peso_Nascimento")
                        .HasPrecision(4, 3)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id_Mae");

                    b.HasIndex("Id_Parto");

                    b.ToTable("Bebe", (string)null);
                });

            modelBuilder.Entity("ex2.Models.MaeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mae", (string)null);
                });

            modelBuilder.Entity("ex2.Models.MedicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<int>("Celular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("ex2.Models.PartoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data_Parto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Horario_Parto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id_Medico")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id_Medico");

                    b.ToTable("Parto", (string)null);
                });

            modelBuilder.Entity("ex2.Models.BebeModel", b =>
                {
                    b.HasOne("ex2.Models.MaeModel", "Mae")
                        .WithMany("Bebes")
                        .HasForeignKey("Id_Mae")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mae");

                    b.HasOne("ex2.Models.PartoModel", "Parto")
                        .WithMany("Bebes")
                        .HasForeignKey("Id_Parto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Parto");

                    b.Navigation("Mae");

                    b.Navigation("Parto");
                });

            modelBuilder.Entity("ex2.Models.PartoModel", b =>
                {
                    b.HasOne("ex2.Models.MedicoModel", "Medico")
                        .WithMany("Partos")
                        .HasForeignKey("Id_Medico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Medico");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ex2.Models.MaeModel", b =>
                {
                    b.Navigation("Bebes");
                });

            modelBuilder.Entity("ex2.Models.MedicoModel", b =>
                {
                    b.Navigation("Partos");
                });

            modelBuilder.Entity("ex2.Models.PartoModel", b =>
                {
                    b.Navigation("Bebes");
                });
#pragma warning restore 612, 618
        }
    }
}
