services: # define quais serviços que o docker irá criar
 db: # nome do serviço db
    image: postgres # imagem do serviço
    restart: always # sempre que eu executar o docker compose up ele irá restartar o db
    environment: # variaveis de ambiente
      POSTGRES_PASSWORD: example # define o valor da variavel de senha do postgres
    volumes: # partição virtual no docker
      - postgres-data:/var/lib/postgresql/data
 app: # serviço app
    build: 
      context: . # executa o dockerfile no diretório onde está o docker-compose.yml
    ports:
      - 5000:80 # a porta exposta é 5000
    depends_on:
      - db # o app depende que o db exista
volumes:
 postgres-data:
